# Generated by Django 4.2.6 on 2024-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_keycloak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, help_text='Patient Identifier', max_length=500, null=True, unique=True),
        ),
    ]
