# Generated by Django 4.2.6 on 2024-02-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_keycloak_id_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('patient_profile', 'Patient Profile')], default='patient-profile', help_text='Classification of the resource', max_length=30),
            preserve_default=False,
        ),
    ]
