# Generated by Django 4.2.6 on 2024-02-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_resource_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('user', 'type')},
        ),
    ]
