# Generated by Django 4.2.6 on 2024-02-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_resource_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, help_text='Street name, number or P.O. Box', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(choices=[('', '-----'), ('DE', 'Germany'), ('TR', 'Turkey'), ('TRNC', 'Turkish Republic of North Cyprus'), ('CY', 'Cyprus'), ('BE', 'Belgium'), ('DK', 'Denmark'), ('FR', 'France'), ('LU', 'Luxembourg'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('PL', 'Poland'), ('CH', 'Switzerland'), ('LI', 'Liechtenstein')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
    ]
