# Generated by Django 4.2.6 on 2024-02-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_city_address__city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='_city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='_country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='_postal_code',
        ),
        migrations.RemoveField(
            model_name='address',
            name='_state',
        ),
    ]
