# Generated by Django 4.2.6 on 2024-02-27 13:49

from django.db import migrations
import django.db.models.fields
import users.fields
import users.pseudonymize_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_address__city_remove_address__country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='_line',
        ),
        migrations.AddField(
            model_name='address',
            name='line',
            field=users.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.CharField, max_length=100, methods=(users.pseudonymize_utils.mask, users.pseudonymize_utils.unmask)),
        ),
    ]
