# Generated by Django 4.2.6 on 2024-02-27 14:16

from django.db import migrations
import django.db.models.fields
import users.fields
import users.pseudonymize_utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_address__line_address_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=users.fields.PseudonymizedField(choices=[('', '-----'), ('DE', 'Germany'), ('TR', 'Turkey'), ('TRNC', 'Turkish Republic of North Cyprus'), ('CY', 'Cyprus'), ('BE', 'Belgium'), ('DK', 'Denmark'), ('FR', 'France'), ('LU', 'Luxembourg'), ('NL', 'Netherlands'), ('AT', 'Austria'), ('CZ', 'Czech Republic'), ('PL', 'Poland'), ('CH', 'Switzerland'), ('LI', 'Liechtenstein')], default='DE', field_type=django.db.models.fields.CharField, max_length=100, methods=(users.pseudonymize_utils.mask, users.pseudonymize_utils.unmask)),
            preserve_default=False,
        ),
    ]
