# Generated by Django 4.2.6 on 2023-10-08 11:37
from datetime import datetime
from django.db import migrations

def seed(apps, schema_editor):
    Author = apps.get_model("authormgmt", "Athor") # NOTE: This also contains the typo that represents a mistake!
    db_alias = schema_editor.connection.alias
    Author.objects.using(db_alias).bulk_create(
        [
            Author(name="J.K Rowling", birthday=datetime(year=1965, month=7, day=31)),
            Author(name="J. R. R. Tolkien", birthday=datetime(year=1892, month=1, day=3)),
            Author(name="Brandon Sanderson", birthday=datetime(year=1975, month=12, day=19)),
            Author(name="Patrick Rothfuss", birthday=datetime(year=1973, month=6, day=6)),
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('authormgmt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed)
    ]
