# Generated by Django 4.2.6 on 2023-10-08 11:37

from django.db import migrations

def seed(apps, schema_editor):
    Book = apps.get_model("bookstore", "Book")
    db_alias = schema_editor.connection.alias
    Book.objects.using(db_alias).bulk_create(
        [
            Book(title="Harry Potter und die Kammer des Schreckens", price=10),
            Book(title="Der Herr der Ringe", price=15),
            Book(title="Der Weg der Könige", price=11),
            Book(title="Der Name des Windes", price=13)
        ]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed)
    ]
