# Generated by Django 4.2.6 on 2023-10-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # NOTE how" python manage.py makemigrations bookstore determined the dependency between both django apps"
        ('authormgmt', '0002_seed_database'),
        ('bookstore', '0002_seed_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authormgmt.athor'),
        ),
    ]
