# Generated by Django 4.2.6 on 2023-10-08 15:43

from django.db import migrations

def makeFkAuthorConnections(apps, schema_editor):
    connections = {
        "Harry Potter und die Kammer des Schreckens": "J.K Rowling",
        "Der Herr der Ringe": "J. R. R. Tolkien",
        "Der Weg der Könige": "Brandon Sanderson",
        "Der Name des Windes": "Patrick Rothfuss"
    }

    Book = apps.get_model("bookstore", "Book")
    Author = apps.get_model("authormgmt", "Author")
    db_alias = schema_editor.connection.alias

    books = Book.objects.using(db_alias).all()
    authors = Author.objects.using(db_alias).all()

    authorByName = {}
    for a in authors:
        authorByName[a.name] = a

    for b in books:
        if b.title in connections.keys():
            b.author = authorByName[connections[b.title]]
            b.save()




class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_author'),
    ]

    operations = [
        migrations.RunPython(makeFkAuthorConnections)
    ]