# Generated by Django 4.2.6 on 2024-02-19 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pseudonymized_PII',
        ),
        migrations.DeleteModel(
            name='PseudonymizedPersonalIdentifyableInformation',
        ),
    ]
