# Generated by Django 4.2.6 on 2024-02-19 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0003_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PMI',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ehr.personalmedicalinformation'),
        ),
    ]
