"""
Django settings for django_project project.

Generated by 'django-admin startproject' using Django 4.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iw@%e_ja$*b-6sk^tsylhvim)37$=u60)74)u%nk5@9^@i&m2n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'mozilla_django_oidc',  # Load after auth
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'bookstore.apps.BookstoreConfig',
    'authormgmt.apps.AuthormgmtConfig',
    'ehr.apps.EhrConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
    'users.middleware.ConsentCheckMiddleware',
]

ROOT_URLCONF = 'django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "postgres",
        "USER": "postgres",
        "PASSWORD": "curiescience",
        "HOST": "db.curiescience.com",  # set in docker-compose.yml
        "PORT": 5432,  # default postgres port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# Add 'mozilla_django_oidc' authentication backend
AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.ModelBackend', # Admin user needs to log in through keycloak
    'users.auth.OIDCAuthenticationBackend',
)

# https://phasetwo.io/blog/secure-django/#setting-up-a-keycloak-instance
# OIDC Configuration
OIDC_RP_CLIENT_ID = 'turbo'
OIDC_RP_CLIENT_SECRET = 'y4SPiSpCC5cKBA7oc8E9SNtcxfMCTP2E'

OIDC_REALM = 'master'
OIDC_HOST = 'http://iam.curiescience.com:8080'

OIDC_OP_AUTHORIZATION_ENDPOINT = os.getenv('OIDC_OP_AUTHORIZATION_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/auth')
OIDC_OP_TOKEN_ENDPOINT = os.getenv('OIDC_OP_TOKEN_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/token')
OIDC_OP_USER_ENDPOINT = os.getenv('OIDC_OP_USER_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/userinfo')
OIDC_OP_JWKS_ENDPOINT = os.getenv('OIDC_OP_JWKS_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/certs')
OIDC_OP_LOGOUT_ENDPOINT = os.getenv('OIDC_OP_LOGOUT_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/protocol/openid-connect/logout')
UMA_PROTECTION_API_RESOURCE = os.getenv('UMA_PROTECTION_API_RESOURCE',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/authz/protection/resource_set')
UMA_PROTECTION_API_PERMISSION = os.getenv('UMA_PROTECTION_API_PERMISSION',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/authz/protection/permission')
UMA_PROTECTION_API_POLICY = os.getenv('UMA_PROTECTION_API_POLICY',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/authz/protection/uma-policy')
OIDC_CONSENT_ENDPOINT = os.getenv('OIDC_CONSENT_ENDPOINT',
    f'{OIDC_HOST}/admin/realms/{OIDC_REALM}/users')
OIDC_EXTENSION_CONSENT_ENDPOINT = os.getenv('OIDC_EXTENSION_CONSENT_ENDPOINT',
    f'{OIDC_HOST}/realms/{OIDC_REALM}/custom-consent')

OIDC_OP_LOGOUT_URL_METHOD = 'users.auth_utils.oidc_op_logout'
OIDC_USERNAME_ALGO = 'users.auth_utils.generate_username'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_RP_SCOPES = 'openid email'
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True  # Needs to be stored as it is used as id_token_hint for logout
OIDC_EXEMPT_URLS = ['/auth']


LOGIN_URL = 'oidc_authentication_init'
LOGIN_REDIRECT_URL = '/ehr'
LOGOUT_REDIRECT_URL = '/auth'

GPAS_DOMAIN_NAME = os.getenv('GPAS_DOMAIN_NAME',
    'TurboChainsaw')
GPAS_WSDL_URL = os.getenv('GPAS_WSDL_URL',
    'http://gpas-wildfly:8080/gpas/gpasService?wsdl')